//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueSharp.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeagueSharp.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   查詢類似 {
        ///	&quot;\u003c&quot;: &quot;\u003c&quot;,
        ///	&quot;yasuo&quot;: &quot;\u72bd\u5bbf&quot;,
        ///  &quot;velkoz&quot;: &quot;\u5a01\u5bc7\u8332&quot;,
        ///  &quot;braum&quot;: &quot;\u5e03\u90ce\u59c6&quot;,
        ///  &quot;gnar&quot;: &quot;\u5436\u5152&quot;,
        ///  &quot;azir&quot;: &quot;\u963f\u7948\u723e&quot;,
        ///  &quot;kalista&quot;: &quot;\u514b\u9ece\u601d\u59b2&quot;,
        ///  &quot;rekSai&quot;: &quot;\u96f7\u73c2\u715e&quot;,
        ///  &quot;bard&quot;: &quot;\u5df4\u5fb7&quot;,
        ///  &quot;ekko&quot;: &quot;\u827e\u514b&quot;,
        ///  &quot;aatrox&quot;: &quot;\u5384\u85a9\u65af&quot;,
        ///  &quot;ahri&quot;: &quot;\u963f\u7483&quot;,
        ///  &quot;akali&quot;: &quot;\u963f\u5361\u8389&quot;,
        ///  &quot;alistar&quot;: &quot;\u4e9e\u6b77\u65af\u5854&quot;,
        ///  &quot;amumu&quot;: &quot;\u963f\u59c6\u59c6&quot;,
        ///  &quot;anivia&quot;: &quot;\u827e\u59ae\u7dad\u4e9e&quot;,
        ///  &quot;annie&quot;: &quot;\u5b89\u59ae&quot;,
        ///  &quot;ashe&quot;: &quot;\u827e\u5e0c&quot;,
        ///  &quot;blitzcrank&quot;: &quot;\u5e03\u91cc\u8328&quot;,
        ///  &quot;brand&quot;: &quot;\u5e03\u862d\u5fb7&quot;,
        ///  &quot;caitlyn&quot;: &quot;\u51f1\u7279\u7433&quot;,
        ///  &quot;cassiopeia&quot;: &quot;\u5361\u838e\u78a7\u96c5&quot;,
        ///  &quot;chogath&quot;: &quot;\u79d1\u52a0\u65af&quot;,
        ///  &quot;corki&quot;: &quot;\u5eab\u5947&quot;,
        ///  &quot;darius&quot;: &quot;\u9054\u745e\u65af&quot;,
        ///  &quot;diana&quot;: &quot;\u9edb\u5b89\u5a1c&quot;,
        ///  &quot;drmundo&... 的當地語系化字串。
        /// </summary>
        internal static string ChineseJson {
            get {
                return ResourceManager.GetString("ChineseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CPActiveSlider {
            get {
                object obj = ResourceManager.GetObject("CPActiveSlider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CPForm {
            get {
                object obj = ResourceManager.GetObject("CPForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CPInactiveSlider {
            get {
                object obj = ResourceManager.GetObject("CPInactiveSlider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
